version: "3"
services:
  backend-a:
    image: backend-a:latest
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      dbnet:
        aliases:
         - backend-a
  backend-b:
    image: backend-b:latest
    ports:
      - "5433:5432"
    environment:
      - -c hot_standby=true
      - -c hot_standby_feedback=true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      dbnet:
        aliases:
         - backend-b
networks:
  dbnet:
