#!/bin/bash
#set -eo pipefail

host="$(hostname -i || echo '127.0.0.1')"
user="${POSTGRES_USER:-postgres}"
db="${POSTGRES_DB:-$POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD:-}"

#ready=`pg_isready -h backend-b -p 5432 | echo $?`
#if [ "$ready" == 0 ]; then
#	echo  "[INFO] postgresql running - continue."
#else
#	pg_ctl promote -D /var/lib/postgresql/data
#fi

args=(
	# force postgres to not use the local unix socket (test "external" connectibility)
	--host "$host"
	--username "$user"
	--dbname "$db"
	--quiet --no-align --tuples-only
)

if select="$(echo 'SELECT 1' | psql "${args[@]}")" && [ "$select" = '1' ]; then
	exit 0
fi

exit 1
